# task 1

In [1]:
import numpy as np


In [2]:
import numpy as np
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [3]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
m=np.arange(1,100,2)
m

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [5]:
m=np.arange(1,100,9)

In [2]:
m=np.arange(1,60,1)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [6]:
hr=np.arange(1,501,1)
hr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [3]:
n=[[1,2,3],[33,23,45]]


[[1, 2, 3], [33, 23, 45]]

In [1]:
import pandas as pd

In [2]:
data=listings[listings['host_is_superhost']=='t']
data2=listings[listings['host_is_superhost']=='f']
data_avg=data.groupby('neighbourhood_cleansed')['price'].mean()
data2_avg=data2.groupby('neighbourhood_cleansed')['price'].mean()
price_diffrence=data_avg-data2_avg
maximun_diffrence= price_diffrence.idxmax()
maximun_diffrence=price_diffrence.max()


NameError: name 'listings' is not defined

In [4]:
#comany wise to allot the employ code
hr=np.arange(1,501,1,int)
finc=np.arange(501,1001,1,int)
it=np.arange(1001,1501,1,int)
sales=np.arange(1501,2001,1,int)




In [6]:
n=np.arange(1,100,2,int)

In [3]:
sh=np.arange(1,23,1)

In [7]:
n.shape

(50,)

In [4]:
hr=np.arange(1,50,1,int)


In [ ]:
it=np.arange

In [5]:
fin=np.arange(1,45,1,int)
it=np.arange(1,100,1,int)
sales=np.arange(2,70,1,int)

In [34]:
hr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [10]:
finc

array([ 501,  502,  503,  504,  505,  506,  507,  508,  509,  510,  511,
        512,  513,  514,  515,  516,  517,  518,  519,  520,  521,  522,
        523,  524,  525,  526,  527,  528,  529,  530,  531,  532,  533,
        534,  535,  536,  537,  538,  539,  540,  541,  542,  543,  544,
        545,  546,  547,  548,  549,  550,  551,  552,  553,  554,  555,
        556,  557,  558,  559,  560,  561,  562,  563,  564,  565,  566,
        567,  568,  569,  570,  571,  572,  573,  574,  575,  576,  577,
        578,  579,  580,  581,  582,  583,  584,  585,  586,  587,  588,
        589,  590,  591,  592,  593,  594,  595,  596,  597,  598,  599,
        600,  601,  602,  603,  604,  605,  606,  607,  608,  609,  610,
        611,  612,  613,  614,  615,  616,  617,  618,  619,  620,  621,
        622,  623,  624,  625,  626,  627,  628,  629,  630,  631,  632,
        633,  634,  635,  636,  637,  638,  639,  640,  641,  642,  643,
        644,  645,  646,  647,  648,  649,  650,  6

In [6]:
it

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011,
       1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022,
       1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033,
       1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044,
       1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055,
       1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066,
       1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077,
       1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088,
       1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099,
       1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110,
       1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121,
       1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132,
       1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143,
       1144, 1145, 1146, 1147, 1148, 1149, 1150, 11

In [7]:
sales

array([1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511,
       1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522,
       1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533,
       1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544,
       1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555,
       1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566,
       1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577,
       1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588,
       1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599,
       1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610,
       1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621,
       1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632,
       1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643,
       1644, 1645, 1646, 1647, 1648, 1649, 1650, 16

# task 2

In [7]:
#salary of all employees of each department
hr_salry=np.random.randint(25000,50001,500,int)
hr_salry

array([31262, 36292, 40899, 26998, 34393, 47883, 31220, 47662, 32802,
       34567, 32059, 34350, 27631, 26051, 28489, 30143, 28428, 42654,
       31848, 37892, 33289, 35555, 34917, 44511, 28983, 25503, 47380,
       30824, 46110, 30756, 26145, 28489, 40377, 31541, 37657, 31273,
       29082, 49690, 37854, 30607, 28723, 31206, 44814, 37612, 26146,
       30043, 45248, 28054, 41823, 25640, 33424, 33884, 28669, 30954,
       41741, 31801, 39609, 37286, 40813, 44478, 49933, 49267, 26231,
       40178, 38719, 32515, 29492, 45997, 47316, 36414, 46798, 25836,
       27200, 40509, 47542, 33436, 48647, 33351, 30307, 26439, 26860,
       32860, 45214, 40730, 33168, 34742, 49607, 44100, 39878, 28832,
       47326, 39641, 36559, 28588, 42212, 29447, 34010, 42047, 40042,
       48224, 31785, 43823, 30547, 26299, 35450, 44539, 40174, 25853,
       42774, 43792, 36859, 34408, 35213, 37220, 48070, 45580, 48974,
       33827, 35757, 45223, 41962, 47491, 42809, 41218, 25488, 47540,
       27536, 39313,

In [14]:
np.random.randint(1,100,5)

array([87, 69, 21, 96, 16])

In [121]:
finance_salary=0.25*hr_salry+hr_salry
finance_salary

array([56138.75, 35530.  , 48603.75, 62105.  , 60191.25, 57487.5 ,
       59045.  , 41956.25, 53773.75, 44795.  , 57347.5 , 43712.5 ,
       37171.25, 34425.  , 35015.  , 46912.5 , 60281.25, 48306.25,
       51536.25, 32703.75, 49780.  , 38751.25, 34176.25, 36702.5 ,
       60687.5 , 44590.  , 31302.5 , 38367.5 , 32125.  , 37251.25,
       44766.25, 45846.25, 62491.25, 54900.  , 47401.25, 36511.25,
       49007.5 , 40265.  , 44617.5 , 48220.  , 46302.5 , 41152.5 ,
       46798.75, 51966.25, 45881.25, 34437.5 , 55525.  , 58917.5 ,
       40695.  , 43242.5 , 50721.25, 38191.25, 59683.75, 60431.25,
       37996.25, 61530.  , 31422.5 , 54121.25, 40235.  , 53952.5 ,
       32868.75, 50062.5 , 53402.5 , 57106.25, 32108.75, 40222.5 ,
       55513.75, 39295.  , 47423.75, 56670.  , 33807.5 , 37455.  ,
       54128.75, 33260.  , 40747.5 , 41195.  , 49692.5 , 32148.75,
       58425.  , 32717.5 , 57913.75, 60065.  , 31868.75, 58907.5 ,
       57823.75, 62355.  , 44426.25, 44316.25, 40132.5 , 48782

In [122]:
sales_salary=finance_salary/2

In [179]:
sales_salary

array([30876.3125, 19541.5   , 26732.0625, 34157.75  , 33105.1875,
       31618.125 , 32474.75  , 23075.9375, 29575.5625, 24637.25  ,
       31541.125 , 24041.875 , 20444.1875, 18933.75  , 19258.25  ,
       25801.875 , 33154.6875, 26568.4375, 28344.9375, 17987.0625,
       27379.    , 21313.1875, 18796.9375, 20186.375 , 33378.125 ,
       24524.5   , 17216.375 , 21102.125 , 17668.75  , 20488.1875,
       24621.4375, 25215.4375, 34370.1875, 30195.    , 26070.6875,
       20081.1875, 26954.125 , 22145.75  , 24539.625 , 26521.    ,
       25466.375 , 22633.875 , 25739.3125, 28581.4375, 25234.6875,
       18940.625 , 30538.75  , 32404.625 , 22382.25  , 23783.375 ,
       27896.6875, 21005.1875, 32826.0625, 33237.1875, 20897.9375,
       33841.5   , 17282.375 , 29766.6875, 22129.25  , 29673.875 ,
       18077.8125, 27534.375 , 29371.375 , 31408.4375, 17659.8125,
       22122.375 , 30532.5625, 21612.25  , 26083.0625, 31168.5   ,
       18594.125 , 20600.25  , 29770.8125, 18293.    , 22411.1

In [180]:
it_salry=hr_salry+5000

In [181]:
it_salry

array([49911, 33424, 43883, 54684, 53153, 50990, 52236, 38565, 48019,
       40836, 50878, 39970, 34737, 32540, 33012, 42530, 53225, 43645,
       46229, 31163, 44824, 36001, 32341, 34362, 53550, 40672, 30042,
       35694, 30700, 34801, 40813, 41677, 54993, 48920, 42921, 34209,
       44206, 37212, 40694, 43576, 42042, 37922, 42439, 46573, 41705,
       32550, 49420, 52134, 37556, 39594, 45577, 35553, 52747, 53345,
       35397, 54224, 30138, 48297, 37188, 48162, 31295, 45050, 47722,
       50685, 30687, 37178, 49411, 36436, 42939, 50336, 32046, 34964,
       48303, 31608, 37598, 37956, 44754, 30719, 51740, 31174, 51331,
       53052, 30495, 52126, 51259, 54884, 40541, 40453, 37106, 44026,
       53217, 30849, 49668, 41385, 53906, 48967, 35237, 46577, 48025,
       33670, 43104, 35093, 43983, 31281, 44488, 30632, 50782, 52423,
       44232, 31066, 31230, 33637, 42633, 31405, 41815, 49962, 51360,
       30842, 44801, 36922, 33374, 42074, 48548, 33381, 32423, 54378,
       50228, 31111,

# task 3

In [124]:
#total expenses of the company
hrtotal=np.sum(hr_salry)
hrtotal

18626664

In [9]:
np.sum(hr_salry)

18485368

In [6]:
hrtotal=np.sum(hr)

In [ ]:
hrtotal=np

In [125]:
finctotal=np.sum(finance_salary)
hrtotal

18626664

In [126]:
salestotal=np.sum(sales_salary)
salestotal

11641665.0

In [127]:
ittotal=np.sum(it_salry)
ittotal

21126664

In [128]:
departmentexp=np.array([hrtotal,finctotal,salestotal,ittotal],int)
departmentexp

array([18626664, 23283330, 11641665, 21126664])

In [129]:
departmentexp.sort()
print(departmentexp)

[11641665 18626664 21126664 23283330]


# task 4

In [8]:
# top 10 higest salaries
a=hr


In [9]:
np.sort(a)[::-1][0:10]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40])

In [15]:
np.sort(hr)[::-1][1:10]

array([48, 47, 46, 45, 44, 43, 42, 41, 40])

In [119]:
np.sort(a)[::-1][0:10]

array([49993, 49977, 49884, 49796, 49738, 49728, 49719, 49684, 49656,
       49573])

In [131]:
b=finance_salary

In [ ]:
grid = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [4]:
shahid=[[12,23,34,56,],[2737,244,234,234,],[47363,3663,989]]
print(shahid)


[[12, 23, 34, 56], [2737, 244, 234, 234], [47363, 3663, 989]]


In [8]:
s=[[2233,456,667,677,],[3456,3455,555],[24,34,345,345,34]]
print('two dimension labeled array =',s)

two dimension labeled array = [[2233, 456, 667, 677], [3456, 3455, 555], [24, 34, 345, 345, 34]]


In [10]:
sd=[[12,34,56,89,986,44,3],[445,4346,7,775,44,3],[344,56,78,86,543,34,5,6]]
sd

[[12, 34, 56, 89, 986, 44, 3],
 [445, 4346, 7, 775, 44, 3],
 [344, 56, 78, 86, 543, 34, 5, 6]]

In [132]:
np.sort(b)[::-1][0:10]

array([62491.25, 62471.25, 62355.  , 62245.  , 62172.5 , 62160.  ,
       62148.75, 62105.  , 62070.  , 61966.25])

# task 5

In [178]:
#no of employees salary more than 45000
x=sales_salary[np.where(sales_salary>45000)]
x=x*1.1
x.size


0

In [19]:
y=hr[np.where(it>45000)]
u=y*1.1
u.size

0

In [182]:
y=it_salry[np.where(it_salry>45000)]
y=y*1.1
y.size



187

# task 6

In [159]:
# update the salary record in the main recordof the company salaries in the sales dept
x_10=sales_salary<45000
sales_salary[x_10]=sales_salary[x_10]*.10+sales_salary[x_10]

In [160]:
sales_salary[x_10]

array([30876.3125, 19541.5   , 26732.0625, 34157.75  , 33105.1875,
       31618.125 , 32474.75  , 23075.9375, 29575.5625, 24637.25  ,
       31541.125 , 24041.875 , 20444.1875, 18933.75  , 19258.25  ,
       25801.875 , 33154.6875, 26568.4375, 28344.9375, 17987.0625,
       27379.    , 21313.1875, 18796.9375, 20186.375 , 33378.125 ,
       24524.5   , 17216.375 , 21102.125 , 17668.75  , 20488.1875,
       24621.4375, 25215.4375, 34370.1875, 30195.    , 26070.6875,
       20081.1875, 26954.125 , 22145.75  , 24539.625 , 26521.    ,
       25466.375 , 22633.875 , 25739.3125, 28581.4375, 25234.6875,
       18940.625 , 30538.75  , 32404.625 , 22382.25  , 23783.375 ,
       27896.6875, 21005.1875, 32826.0625, 33237.1875, 20897.9375,
       33841.5   , 17282.375 , 29766.6875, 22129.25  , 29673.875 ,
       18077.8125, 27534.375 , 29371.375 , 31408.4375, 17659.8125,
       22122.375 , 30532.5625, 21612.25  , 26083.0625, 31168.5   ,
       18594.125 , 20600.25  , 29770.8125, 18293.    , 22411.1

# part 2

In [136]:
data=np.genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv',delimiter=',' ,skip_header=1)
data

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [21]:
data=np.genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv',delimiter=' ,',skip_header=1)

# task 1

In [153]:
#total no of students whoes gre score is  greater than 320
gre_score=data[:,1]
x=gre_score[np.where(gre_score>320)]
x

array([337., 324., 322., 330., 321., 323., 325., 327., 328., 325., 328.,
       334., 336., 340., 322., 327., 338., 340., 331., 332., 326., 322.,
       329., 339., 321., 327., 334., 324., 322., 325., 325., 327., 328.,
       332., 336., 321., 329., 327., 340., 322., 340., 331., 332., 323.,
       322., 326., 329., 338., 331., 321., 327., 335., 334., 323., 326.,
       333., 339., 323., 333., 326., 329., 332., 331., 340., 325., 326.,
       339., 334., 332., 321., 324., 326., 329., 322., 334., 322., 323.,
       321., 329., 327., 335., 331., 324., 324., 323., 322., 336., 340.,
       334., 325., 328., 338., 333., 331., 330., 322., 321., 324., 324.,
       324., 330., 326., 325., 329., 324., 325., 328., 324., 321., 335.,
       321., 324., 326., 331., 327., 324., 325., 327., 322., 329., 321.,
       340., 331., 336., 324., 330., 322., 323., 321., 323., 325., 328.,
       324., 327., 323., 326., 324., 327., 325., 332., 323., 324., 326.,
       325., 327., 321., 322., 334., 338., 330., 32

# task 2

In [151]:
#admission possibility ofbstudents who have a toefl greater than 110
x=data[:,2]
data[x>110,8][::-1]

array([0.95, 0.91, 0.89, 0.84, 0.96, 0.96, 0.95, 0.86, 0.91, 0.93, 0.94,
       0.83, 0.8 , 0.8 , 0.81, 0.8 , 0.79, 0.8 , 0.71, 0.9 , 0.86, 0.89,
       0.92, 0.93, 0.94, 0.8 , 0.89, 0.83, 0.7 , 0.9 , 0.85, 0.93, 0.77,
       0.76, 0.7 , 0.86, 0.85, 0.88, 0.91, 0.82, 0.71, 0.76, 0.91, 0.93,
       0.94, 0.96, 0.95, 0.97, 0.97, 0.94, 0.86, 0.9 , 0.88, 0.93, 0.93,
       0.89, 0.9 , 0.85, 0.87, 0.89, 0.89, 0.81, 0.86, 0.94, 0.93, 0.96,
       0.83, 0.81, 0.8 , 0.97, 0.92, 0.9 , 0.8 , 0.89, 0.79, 0.96, 0.92,
       0.84, 0.78, 0.85, 0.94, 0.94, 0.93, 0.91, 0.87, 0.74, 0.79, 0.9 ,
       0.86, 0.94, 0.92, 0.96, 0.74, 0.72, 0.93, 0.96, 0.94, 0.78, 0.61,
       0.55, 0.52, 0.72, 0.78, 0.78, 0.89, 0.86, 0.91, 0.87, 0.94, 0.9 ,
       0.91, 0.94, 0.97, 0.95, 0.94, 0.7 , 0.78, 0.84, 0.9 , 0.92])

# task 3

In [170]:
# the series of numbers of all the students who r elegible and determine theno of these students
s=data[:,1]
d=data[:,2]

In [171]:
data[s>315,0]

array([  1.,   2.,   3.,   4.,   6.,   7.,  10.,  11.,  12.,  13.,  17.,
        18.,  19.,  22.,  23.,  24.,  25.,  26.,  27.,  32.,  33.,  34.,
        35.,  36.,  42.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  53.,
        54.,  55.,  56.,  57.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
        72.,  73.,  76.,  77.,  82.,  83.,  84.,  85.,  86.,  88.,  90.,
        91.,  98.,  99., 100., 101., 104., 105., 106., 107., 108., 109.,
       112., 114., 120., 121., 122., 127., 128., 129., 130., 131., 134.,
       135., 138., 139., 140., 141., 142., 143., 144., 145., 146., 148.,
       149., 151., 152., 153., 154., 155., 163., 164., 165., 166., 172.,
       173., 174., 175., 176., 177., 178., 185., 186., 187., 188., 189.,
       190., 191., 192., 193., 194., 195., 201., 203., 204., 211., 212.,
       213., 214., 215., 216., 217., 218., 219., 222., 223., 229., 230.,
       232., 235., 236., 237., 238., 242., 243., 244., 246., 247., 249.,
       250., 251., 252., 253., 254., 255., 258., 25

In [173]:
data[d>115,0]

array([  1.,  23.,  24.,  25.,  26.,  33.,  44.,  48.,  53.,  71.,  82.,
        98.,  99., 108., 109., 121., 122., 130., 139., 142., 144., 149.,
       152., 172., 177., 188., 194., 203., 204., 213., 214., 215., 216.,
       260., 286., 287., 298., 326., 338., 362., 373., 386., 398., 400.])

In [175]:
data[((s>315) & (d>115)),0]

array([  1.,  23.,  24.,  25.,  26.,  33.,  44.,  48.,  53.,  71.,  82.,
        98.,  99., 108., 109., 121., 122., 130., 139., 142., 144., 149.,
       152., 172., 177., 188., 194., 203., 204., 213., 214., 215., 216.,
       260., 286., 287., 298., 326., 338., 362., 373., 386., 398., 400.])