# task 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
import numpy as np

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import numpy as np
import pandas as pd

In [1]:
import  numpy as np
import pandas as pd

In [1]:
import numpy as np 
import pandas as pd

In [4]:
data=pd.read_csv('DS1_C4_S1_Employee_Data_Challenge.csv')

In [4]:
data=pd.read_csv('DS1_C4_S1_Employee_Data_Challenge.csv')

In [5]:
data

Emp_code  Age
0          1   22
1          2   27
2          3   31
3          4   29
4          5   27
5          6   26
6          7   27
7          8   23
8          9   27
9         10   32
10        11   28
11        12   27
12        13   22
13        14   27
14        15   35
15        16   33
16        17   28
17        18   22
18        19   25
19        20   27
20        21   37
21        22   27
22        23   24
23        24   27
24        25   28
25        26   26
26        27   27
27        28   27
28        29   29
29        30   49
30        31   26
31        32   32
32        33   26
33        34   24
34        35   24
35        36   23
36        37   28
37        38   28
38        39   22
39        40   26
40        41   32
41        42   35
42        43   33
43        44   31
44        45   30
45        46   36
46        47   22
47        48   23
48        49   32
49        50   34

In [3]:
data

Emp_code  Age
0          1   22
1          2   27
2          3   31
3          4   29
4          5   27
5          6   26
6          7   27
7          8   23
8          9   27
9         10   32
10        11   28
11        12   27
12        13   22
13        14   27
14        15   35
15        16   33
16        17   28
17        18   22
18        19   25
19        20   27
20        21   37
21        22   27
22        23   24
23        24   27
24        25   28
25        26   26
26        27   27
27        28   27
28        29   29
29        30   49
30        31   26
31        32   32
32        33   26
33        34   24
34        35   24
35        36   23
36        37   28
37        38   28
38        39   22
39        40   26
40        41   32
41        42   35
42        43   33
43        44   31
44        45   30
45        46   36
46        47   22
47        48   23
48        49   32
49        50   34

In [5]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [6]:
data1=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [7]:
s=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [6]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [ ]:
data1=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [8]:
data1=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [9]:
data1

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [4]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [6]:
data1=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter='',skip_header=1)

In [7]:
data1

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [8]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)
data

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [10]:
data1=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [2]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [4]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [8]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [ ]:
,m=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimeter=',',skip_hede1)

In [6]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [5]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

In [6]:
data.mo.genfromnxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',kip_header=1)

AttributeError: 'numpy.ndarray' object has no attribute 'mo'

In [44]:
data

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [4]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)
data

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [2]:
data=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',' ,skip_header=1)
data

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [3]:
s=data[:,1]
a=np.mean(s)
a

28.26

In [14]:
s=data[:]
s.mean()

26.88

In [9]:
d=data1[:1]
c=d.mean()
c

11.5

In [12]:
s=data[:1]
s

array([[ 1., 22.]])

In [11]:
d=data[:1]
g=np.mean(d)

In [13]:
g

11.5

In [7]:
d=data[:,1]
c=np.mean(d)
c

28.26

In [14]:
c=data[:,1]
x=np.mean(c)
x

28.26

In [8]:
d=data[:,0]
n=np.mean(d)
n

25.5

In [3]:
data4=np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv',delimiter=',',skip_header=1)

# task 2

In [16]:
b=data[:,1]
age=b>=25
age

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True])

In [15]:
b=data[:,1]
age=b>=25
age

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True])

In [16]:
c=len(data[age,1])
c

39

In [18]:
c=len(data[age,1])
c

39

In [21]:
hen=data[:,1]
lam=hen>=10
lam

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [22]:
n=len(data[lam,1])
n

50

In [16]:
c=data[:,0]
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [15]:
b=data1[:,0]
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [13]:
b=data[:,1]
age=b>=25
age

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True])

In [18]:
n=data[:,1]
age=n<=25
age

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
        True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
       False, False,  True, False, False, False, False, False, False,
       False,  True,  True, False, False])

In [20]:
g=data[:,1]
age=g>=25
data[age,0:2]

array([[ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [37., 28.],
       [38., 28.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [49., 32.],
       [50., 34.]])

In [21]:
d=len(data[age,1])
print ("total number of employees who are over 25 years old ={}".format(d))

total number of employees who are over 25 years old =39


In [17]:
c=len(data[age,1])

NameError: name 'age' is not defined

# task 3

In [24]:
age=data[:,1]
m=(age>30) & (age<35)
data[m, 0:2]

array([[ 3., 31.],
       [10., 32.],
       [16., 33.],
       [32., 32.],
       [41., 32.],
       [43., 33.],
       [44., 31.],
       [49., 32.],
       [50., 34.]])

In [32]:
age=data[:,1]
m=(age>30) & (age<35)
data[m, 0:2]

array([[ 3., 31.],
       [10., 32.],
       [16., 33.],
       [32., 32.],
       [41., 32.],
       [43., 33.],
       [44., 31.],
       [49., 32.],
       [50., 34.]])

In [29]:
age=data[:,1]
m=(age>30)&(age<35)
data[m,0:5]

array([[ 3., 31.],
       [10., 32.],
       [16., 33.],
       [32., 32.],
       [41., 32.],
       [43., 33.],
       [44., 31.],
       [49., 32.],
       [50., 34.]])

In [15]:
age=data[:,1]
m=(age>30)& (age<35)
data[m,0:2]

array([[ 3., 31.],
       [10., 32.],
       [16., 33.],
       [32., 32.],
       [41., 32.],
       [43., 33.],
       [44., 31.],
       [49., 32.],
       [50., 34.]])

In [17]:
a=len(data[m,1])
print('totrsl no of mployees = {}'.format(a))

totrsl no of mployees = 9


In [58]:
a=len(data[m,1])
print ("total number of employees who are 30 to 35 years old ={}".format(a))

total number of employees who are 30 to 35 years old =9


# part 2

In [23]:
import numpy as np

In [24]:
data2=np.genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',' ,skip_header=1)
data2

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

# task 1

In [25]:
age=data2[:,1]
between=(age>=20) & (age<=24)

In [26]:
data2[between,:]

array([[  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  6.,  22.,  17.,  76.],
       [  8.,  23.,  18.,  94.],
       [ 14.,  24.,  20.,  77.],
       [ 16.,  22.,  20.,  79.],
       [ 18.,  20.,  21.,  66.],
       [ 30.,  23.,  29.,  87.],
       [ 32.,  21.,  30.,  73.],
       [ 36.,  21.,  33.,  81.],
       [ 40.,  20.,  37.,  75.],
       [ 42.,  24.,  38.,  92.],
       [ 46.,  24.,  39.,  65.],
       [ 79.,  23.,  54.,  52.],
       [ 85.,  21.,  54.,  57.],
       [ 88.,  22.,  57.,  55.],
       [ 96.,  24.,  60.,  52.],
       [100.,  20.,  61.,  49.],
       [101.,  23.,  62.,  41.],
       [106.,  21.,  62.,  42.],
       [125.,  23.,  70.,  29.],
       [135.,  20.,  73.,   5.]])

# task 2

In [27]:
s=data2[:,3]
spend_score=s>80
data2[spend_score,:]

array([[  2.,  21.,  15.,  81.],
       [  8.,  23.,  18.,  94.],
       [ 12.,  35.,  19.,  99.],
       [ 20.,  35.,  23.,  98.],
       [ 26.,  29.,  28.,  82.],
       [ 30.,  23.,  29.,  87.],
       [ 34.,  18.,  33.,  92.],
       [ 36.,  21.,  33.,  81.],
       [ 42.,  24.,  38.,  92.],
       [124.,  39.,  69.,  91.],
       [128.,  40.,  71.,  95.],
       [136.,  29.,  73.,  88.],
       [142.,  32.,  75.,  93.],
       [144.,  32.,  76.,  87.],
       [146.,  28.,  77.,  97.],
       [150.,  34.,  78.,  90.],
       [152.,  39.,  78.,  88.],
       [156.,  27.,  78.,  89.],
       [162.,  29.,  79.,  83.],
       [164.,  31.,  81.,  93.],
       [168.,  33.,  86.,  95.],
       [174.,  36.,  87.,  92.],
       [176.,  30.,  88.,  86.],
       [180.,  35.,  93.,  90.],
       [182.,  32.,  97.,  86.],
       [184.,  29.,  98.,  88.],
       [186.,  30.,  99.,  97.],
       [190.,  36., 103.,  85.],
       [194.,  38., 113.,  91.],
       [200.,  30., 137.,  83.]])

# task 3

In [67]:
x=np.sort(data2[:,2])
np.where((data2[:,2]==x[0]) | (data2[:,2]==x[x.size-1]))

(array([  0,   1, 198, 199], dtype=int64),)

In [70]:
data[0]

array([ 1., 22.])

# task 4

In [65]:
data2[(data2[:,3]>75) & (data2[:,2]>35) & (data2[:,1]<45)].shape[0]

26

# task 5

In [19]:
n=np.random.randint(10,50,22)
n

TypeError: randint() got an unexpected keyword argument 'random_state'

In [23]:
c=np.random.randint(10,51,data.shape[0]).reshape(50,1)
b=np.concatenate((data),axis=1)


AxisError: axis 1 is out of bounds for array of dimension 1

In [36]:
f=np.random.randint(10,51,data.shape[0]).reshape(50,1)
n=np.concatenate((data,dis),axis=1)
n

array([[ 1., 22., 24.],
       [ 2., 27., 41.],
       [ 3., 31., 11.],
       [ 4., 29., 21.],
       [ 5., 27., 43.],
       [ 6., 26., 14.],
       [ 7., 27., 48.],
       [ 8., 23., 12.],
       [ 9., 27., 31.],
       [10., 32., 13.],
       [11., 28., 19.],
       [12., 27., 49.],
       [13., 22., 43.],
       [14., 27., 10.],
       [15., 35., 22.],
       [16., 33., 27.],
       [17., 28., 33.],
       [18., 22., 30.],
       [19., 25., 35.],
       [20., 27., 18.],
       [21., 37., 20.],
       [22., 27., 24.],
       [23., 24., 40.],
       [24., 27., 37.],
       [25., 28., 10.],
       [26., 26., 10.],
       [27., 27., 10.],
       [28., 27., 22.],
       [29., 29., 43.],
       [30., 49., 33.],
       [31., 26., 39.],
       [32., 32., 19.],
       [33., 26., 46.],
       [34., 24., 11.],
       [35., 24., 16.],
       [36., 23., 50.],
       [37., 28., 12.],
       [38., 28., 20.],
       [39., 22., 37.],
       [40., 26., 48.],
       [41., 32., 20.],
       [42., 35.

In [43]:
b=np.random.randint(10,51,20)
m=np.concatenate((data,b),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
n=np.random.randint(10,)

In [ ]:
dis=np.random.randint(10,51,data.shape[0]).reshape(50,1)

In [34]:
b=np.random.randint(1,34,43)
b

array([17, 32, 24,  8, 30, 20, 12,  7, 18, 11,  1, 14, 24,  8,  6,  3, 23,
        7, 19, 32, 33, 13, 29, 33, 11, 16, 30, 15, 10, 33,  3, 29,  2, 20,
       14, 14,  1,  7,  6, 19,  6,  5,  2])

In [43]:
np.random.randint(2,7,100)

array([6, 5, 5, 4, 4, 5, 4, 2, 5, 4, 4, 5, 6, 6, 2, 6, 6, 3, 6, 5, 2, 3,
       6, 5, 4, 3, 5, 6, 3, 5, 5, 6, 6, 4, 2, 4, 3, 3, 2, 2, 4, 2, 2, 3,
       3, 5, 6, 4, 3, 4, 4, 5, 2, 4, 5, 3, 5, 2, 4, 3, 3, 6, 6, 2, 2, 3,
       5, 6, 2, 3, 6, 3, 2, 3, 4, 3, 2, 3, 2, 2, 3, 2, 6, 2, 5, 3, 2, 5,
       2, 4, 6, 2, 2, 3, 3, 5, 4, 3, 2, 6])

In [46]:
np.random.randint(2,100,20)

array([49, 68, 62, 22,  5, 33, 41, 42, 30, 48, 66, 47, 63, 82, 35,  5, 90,
       80, 43, 79])

In [6]:
b=np.random.randint(1,34,43)
b

array([29,  7, 30, 19, 22, 31,  7,  6, 26, 15, 16, 14,  4, 33,  3, 25, 32,
       25,  5, 11, 19, 28,  1, 15, 29, 24, 16, 21, 27, 11,  8, 11, 16,  8,
       16, 12,  8,  7, 19,  1, 32,  4, 12])

In [16]:
b=np.random.randint(10,23,data1.shape[0]).reshape(50,1)



14

In [35]:
dis=np.random.randint(10,51,data.shape[0]).reshape(50,1)
g=np.concatenate((data,dis),axis=1)
g

array([[ 1., 22., 24.],
       [ 2., 27., 41.],
       [ 3., 31., 11.],
       [ 4., 29., 21.],
       [ 5., 27., 43.],
       [ 6., 26., 14.],
       [ 7., 27., 48.],
       [ 8., 23., 12.],
       [ 9., 27., 31.],
       [10., 32., 13.],
       [11., 28., 19.],
       [12., 27., 49.],
       [13., 22., 43.],
       [14., 27., 10.],
       [15., 35., 22.],
       [16., 33., 27.],
       [17., 28., 33.],
       [18., 22., 30.],
       [19., 25., 35.],
       [20., 27., 18.],
       [21., 37., 20.],
       [22., 27., 24.],
       [23., 24., 40.],
       [24., 27., 37.],
       [25., 28., 10.],
       [26., 26., 10.],
       [27., 27., 10.],
       [28., 27., 22.],
       [29., 29., 43.],
       [30., 49., 33.],
       [31., 26., 39.],
       [32., 32., 19.],
       [33., 26., 46.],
       [34., 24., 11.],
       [35., 24., 16.],
       [36., 23., 50.],
       [37., 28., 12.],
       [38., 28., 20.],
       [39., 22., 37.],
       [40., 26., 48.],
       [41., 32., 20.],
       [42., 35.

In [11]:
my=[[1,3,4],[3,4,6],[373,36,33]]
print(my)

[[1, 3, 4], [3, 4, 6], [373, 36, 33]]


In [21]:
my=[[12,23,455,6,7,88,9,7],[122,567,321,4,8,32,1],[123,54,3,2,3,56]]
my

[[12, 23, 455, 6, 7, 88, 9, 7],
 [122, 567, 321, 4, 8, 32, 1],
 [123, 54, 3, 2, 3, 56]]

In [15]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [17]:
t=np.random.randint(1,12,45)

In [25]:
h=pd.Series(t)
m=h.columns['shahid'][0]

AttributeError: 'Series' object has no attribute 'columns'

In [4]:
myArray = [[1, 2, 3], [4, 5, 6]]
print(myArray)

[[1, 2, 3], [4, 5, 6]]


In [9]:
myArray = [[1, 2, 3], [4, 5, 6],[45,87,98]]
myArray[2]

[45, 87, 98]

# task 6

In [62]:
dis=np.random.randint(10,51,data2.shape[0]).reshape(200,1)
g=np.concatenate((data2,dis),axis=1)
g[g[:,4]>45]

array([[  1.,  19.,  15.,  39.,  48.],
       [  4.,  23.,  16.,  77.,  47.],
       [ 20.,  35.,  23.,  98.,  49.],
       [ 44.,  31.,  39.,  61.,  49.],
       [ 46.,  24.,  39.,  65.,  48.],
       [ 48.,  27.,  40.,  47.,  48.],
       [ 51.,  49.,  42.,  52.,  46.],
       [ 64.,  54.,  47.,  59.,  47.],
       [ 67.,  43.,  48.,  50.,  46.],
       [ 74.,  60.,  50.,  56.,  46.],
       [ 82.,  38.,  54.,  55.,  46.],
       [106.,  21.,  62.,  42.,  48.],
       [108.,  54.,  63.,  46.,  48.],
       [119.,  51.,  67.,  43.,  46.],
       [125.,  23.,  70.,  29.,  50.],
       [127.,  43.,  71.,  35.,  46.],
       [128.,  40.,  71.,  95.,  47.],
       [137.,  44.,  73.,   7.,  49.],
       [143.,  28.,  76.,  40.,  49.],
       [147.,  48.,  77.,  36.,  49.],
       [158.,  30.,  78.,  78.,  50.],
       [165.,  50.,  85.,  26.,  48.],
       [170.,  32.,  87.,  63.,  46.],
       [174.,  36.,  87.,  92.,  46.],
       [180.,  35.,  93.,  90.,  49.],
       [191.,  34., 103.,